print("I love programming!!!!!")
print("I love genai")
print("I love coding!!!")
print("I love AI!")
print("I love learning new things!")
print("New line")
print("another line")
print("I love solving problems!")
print("latest updates")
